# Default values for demo-nodejs-app-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: vidhya01/nodejsdemo
  pullPolicy: IfNotPresent

  tag: nodejs-app-v7


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  host: nodejs-app.local

