apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodejs-app
  labels:
    app: {{ .Release.Name }}-nodejs-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-nodejs-app
